services:
  - type: pserv
    runtime: image
    name: alpine-chrome
    image:
    url: docker.io/zenika/alpine-chrome:latest

  - type: web
    name: gaugin
    env: go
    region: oregon
    buildCommand: ./render-build.sh
    startCommand: ./gaugin
    healthCheckPath: /
    envVars: