services:
  - type: web
    runtime: image
    name: alpine-chrome
    image:
      url: docker.io/zenika/alpine-chrome:latest

  - type: web
    name: gauguin
    env: go
    region: oregon
    buildCommand: ./render-build.sh
    startCommand: ./gauguin
    healthCheckPath: /
    envVars: